env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 240
    lines: 72
  padding:
    x: 0
    y: 0
  decorations: none
  opacity: 0.95
  startup_mode: Maximized
  class:
    instance: Alacritty
    general: Alacritty
  gtk_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 10

font:
  normal:
    #family: "RobotoMono Nerd Font"
    family: "Iosevka Term"
    style: Regular
  bold:
    #family: "RobotoMono Nerd Font"
    family: "Iosevka Term"
    style: Bold
  italic:
    #family: "RobotoMono Nerd Font"
    family: "Iosevka Term"
    style: Italic
  size: 10.5

draw_bold_text_with_bright_colors: true

# Gruvbox dark {{{
#colors:
#  primary:
#    # hard contrast background - '#1d2021'
#    # normal contrast background - '#282828'
#    background:        &gruvbox_dark_bg '#1d2021'
#    # soft contrast background - '#32302f'
#    foreground:        &gruvbox_dark_fg '#ebdbb2'
#    bright_foreground: '#fbf1c7'
#    dim_foreground:    '#d5c4a1'
#  cursor:
#    text:   CellBackground
#    cursor: CellForeground
#  selection:
#    text:       CellBackground
#    background: CellForeground
#  bright:
#    black:   '#928374'
#    red:     '#fb4934'
#    green:   '#b8bb26'
#    yellow:  '#fabd2f'
#    blue:    '#83a598'
#    magenta: '#d3869b'
#    cyan:    '#8ec07c'
#    white:   *gruvbox_dark_fg
#  normal:
#    black:   *gruvbox_dark_bg
#    red:     '#cc241d'
#    green:   '#98971a'
#    yellow:  '#d79921'
#    blue:    '#458588'
#    magenta: '#b16286'
#    cyan:    '#689d6a'
#    white:   '#a89984'
#  dim:
#    black:   '#32302f'
#    red:     '#9d0006'
#    green:   '#79740e'
#    yellow:  '#b57614'
#    blue:    '#076678'
#    magenta: '#8f3f71'
#    cyan:    '#427b58'
#    white:   '#928374'
  # indexed_colors: []
# }}}

# Nightfly {{{
#colors:
#  # Default colors
#  primary:
#    background:        '#011627'
#    foreground:        '#acb4c2'
#    bright_foreground: '#eeeeee'
#
#  # Cursor colors
#  cursor:
#    text:   '#080808'
#    cursor: '#9ca1aa'
#
#  # Selection colors
#  selection:
#    text:       '#080808'
#    background: '#b2ceee'
#
#  # Normal colors
#  normal:
#    black:   '#1d3b53'
#    red:     '#fc514e'
#    green:   '#a1cd5e'
#    yellow:  '#e3d18a'
#    blue:    '#82aaff'
#    magenta: '#c792ea'
#    cyan:    '#7fdbca'
#    white:   '#a1aab8'
#
#  # Bright colors
#  bright:
#    black:   '#7c8f8f'
#    red:     '#ff5874'
#    green:   '#21c7a8'
#    yellow:  '#ecc48d'
#    blue:    '#82aaff'
#    magenta: '#ae81ff'
#    cyan:    '#7fdbca'
#    white:   '#d6deeb'
# }}}

# Colors (One Half Dark) {{{
colors:
  primary:
    background: '0x282c34'
    foreground: '0xdcdfe4'

  normal:
    black: '0x282c34'
    red: '0xe06c75'
    green: '0x98c379'
    yellow: '0xe5c07b'
    blue: '0x61afef'
    magenta: '0xc678dd'
    cyan: '0x56b6c2'
    white: '0xdcdfe4'

  bright:
    black: '#6C7380'
    red: '0xe06c75'
    green: '0x98c379'
    yellow: '0xe5c07b'
    blue: '0x61afef'
    magenta: '0xc678dd'
    cyan: '0x56b6c2'
    white: '0xdcdfe4'
# }}}

cursor:
  style:
    shape: Block
    blinking: Always

