env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 240
    lines: 72
  padding:
    x: 10
    y: 10
  decorations: none
  opacity: 0.9
  startup_mode: Windowed
  class:
    instance: Alacritty
    general: Alacritty
  gtk_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 10

font:
  normal:
    #family: "RobotoMono Nerd Font"
    family: "Iosevka Term"
    style: Regular
  bold:
    #family: "RobotoMono Nerd Font"
    family: "Iosevka Term"
    style: Bold
  italic:
    #family: "RobotoMono Nerd Font"
    family: "Iosevka Term"
    style: Italic
  size: 10.5

draw_bold_text_with_bright_colors: true

# Gruvbox dark {{{
#colors:
#  primary:
#    # hard contrast background - '#1d2021'
#    # normal contrast background - '#282828'
#    background:        &gruvbox_dark_bg '#1d2021'
#    # soft contrast background - '#32302f'
#    foreground:        &gruvbox_dark_fg '#ebdbb2'
#    bright_foreground: '#fbf1c7'
#    dim_foreground:    '#d5c4a1'
#  cursor:
#    text:   CellBackground
#    cursor: CellForeground
#  selection:
#    text:       CellBackground
#    background: CellForeground
#  bright:
#    black:   '#928374'
#    red:     '#fb4934'
#    green:   '#b8bb26'
#    yellow:  '#fabd2f'
#    blue:    '#83a598'
#    magenta: '#d3869b'
#    cyan:    '#8ec07c'
#    white:   *gruvbox_dark_fg
#  normal:
#    black:   *gruvbox_dark_bg
#    red:     '#cc241d'
#    green:   '#98971a'
#    yellow:  '#d79921'
#    blue:    '#458588'
#    magenta: '#b16286'
#    cyan:    '#689d6a'
#    white:   '#a89984'
#  dim:
#    black:   '#32302f'
#    red:     '#9d0006'
#    green:   '#79740e'
#    yellow:  '#b57614'
#    blue:    '#076678'
#    magenta: '#8f3f71'
#    cyan:    '#427b58'
#    white:   '#928374'
  # indexed_colors: []
# }}}

# Colors One Dark {{{
colors:
  # Default colors
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#ffffff'
# }}}

cursor:
  style:
    shape: Block
    blinking: Always

