require('francisco.lspconfig')
require('francisco.nvim-cmp-lsp')
require('francisco.treesitter')
require('francisco.telescope')
-- require('francisco.lualine')
require('francisco.feline')
require('francisco.alpha-nvim')
require('francisco.bufferline-conf')
require('francisco.nvim-tree')
require('francisco.colorizer')
require('francisco.indentline')
require('francisco.gitsigns')
